In [2]:
import os

import pandas as pd

import numpy as np

import Neuron_analysis as na
#import skimage
#from skimage import io
import SimpleITK as sitk

import re

import napari

import nrrd

In [3]:
viewer = napari.Viewer()

In [4]:
file_name = r'C:/Users/liu/mouse_connectivity/annotation/ccf_2017/annotation_25.nrrd'
data_array, metadata = nrrd.read(file_name)

annot_h=np.moveaxis(data_array, 1, 0)
print('Converted to horizontal atlas with shape', annot_h.shape)
# reslice corontal atlas to horizontal atlas that is consistent with our sample's orientation

atlas_labels=pd.read_csv('D:\Allenbrainatlas\ARA_25_micron_mhd_ccf2017\labels.csv')
#read labels

Converted to horizontal atlas with shape (320, 528, 456)


In [5]:
#viewer.add_image(template, name='template')
viewer.add_labels(annot_h, name='atlas')


<Labels layer 'atlas' at 0x26c4db70b20>

In [6]:
#axons1= sitk.ReadImage(r'D:\viral_results\s2\AL278_axons.tif')
#axons1=sitk.GetArrayFromImage(axons2) 
# issue with image with 64 bit samples, since the normalized images have values like 10e-5

In [10]:
axons=np.load(r'D:\viral_results\AL207.npy')

viewer.add_image(axons)

<Image layer 'axons' at 0x26c5164c0d0>

In [7]:
def create_mask(x):
    #create mask based on selected atlas index (an int)
    mask=np.zeros_like(atlas)
    mask_idx= atlas==x
    mask[mask_idx]=1
    return mask

In [8]:
na.atlas_labels.query('acronym == "stc"')

id  atlas_id                                    name acronym  \
529  484682528       NaN  commissural branch of stria terminalis     stc   

     st_level  ontology_id  hemisphere_id  weight  parent_structure_id  depth  \
529         9            1              3    8690                301.0      5   

     ...  graph_order                 structure_id_path color_hex_triplet  \
529  ...         1260  /997/1009/991/768/301/484682528/            CCCCCC   

    neuro_name_structure_id  neuro_name_structure_id_path  failed sphinx_id  \
529                     NaN                           NaN       f      1261   

     structure_name_facet  failed_facet  \
529            2072512978     734881840   

                                  safe_name  
529  commissural branch of stria terminalis  

[1 rows x 21 columns]

In [16]:
img_id=744
mask=create_mask(img_id)

In [18]:
mask.sum()

0

In [11]:
viewer.add_labels(mask, name=f'{img_id}')

<Labels layer '788' at 0x206550bf668>

In [182]:
na.atlas_labels.query('id == "2933784576"')

Empty DataFrame
Columns: [id, atlas_id, name, acronym, st_level, ontology_id, hemisphere_id, weight, parent_structure_id, depth, graph_id, graph_order, structure_id_path, color_hex_triplet, neuro_name_structure_id, neuro_name_structure_id_path, failed, sphinx_id, structure_name_facet, failed_facet, safe_name]
Index: []

[0 rows x 21 columns]

In [94]:
for i in na.atlas_labels.structure_id_path:
    if '/315/' in i:
        print(i)

/997/8/567/688/695/315/453/12998/
/997/8/567/688/695/315/95/111/163/
/997/8/567/688/695/315/669/561/
/997/8/567/688/695/315/254/894/965/
/997/8/567/688/695/315/95/111/355/
/997/8/567/688/695/315/22/241/
/997/8/567/688/695/315/669/402/1074/
/997/8/567/688/695/315/714/723/412/
/997/8/567/688/695/315/453/322/345/657/
/997/8/567/688/695/315/453/378/
/997/8/567/688/695/315/669/
/997/8/567/688/695/315/254/886/687/
/997/8/567/688/695/315/453/322/345/878/
/997/8/567/688/695/315/184/
/997/8/567/688/695/315/254/879/434/
/997/8/567/688/695/315/453/378/1035/
/997/8/567/688/695/315/453/322/329/1047/
/997/8/567/688/695/315/714/746/680/
/997/8/567/688/695/315/922/368/
/997/8/567/688/695/315/677/
/997/8/567/688/695/315/714/
/997/8/567/688/695/315/247/1027/696/
/997/8/567/688/695/315/669/385/821/
/997/8/567/688/695/315/500/985/320/
/997/8/567/688/695/315/669/385/778/
/997/8/567/688/695/315/184/68/
/997/8/567/688/695/315/247/1011/600/
/997/8/567/688/695/315/95/111/344/
/997/8/567/688/695/315/972/363/
/9

In [11]:
my_list= [i for i in na.atlas_labels.structure_id_path if '/315/' in i]

In [12]:
items= [int(i.split('/')[-2]) for i in my_list]

In [13]:
items=np.asarray(items)

In [10]:
na.atlas_labels.name

0                            extrapyramidal fiber systems
1                            Arcuate hypothalamic nucleus
2                           Somatosensory areas, layer 6b
3       Agranular insular area, posterior part, layer 2/3
4                 Pontine reticular nucleus, ventral part
                              ...                        
1322    Entorhinal area, medial part, ventral zone, la...
1323                                Subgeniculate nucleus
1324                               Dopaminergic A13 group
1325                                columns of the fornix
1326                           direct tectospinal pathway
Name: name, Length: 1327, dtype: object

In [14]:
def create_mask(x):
    #create mask based on selected atlas index (an int)
    mask=np.zeros_like(atlas)
    for i in x:
        mask_idx= atlas==i
        mask[mask_idx]=1
    return mask

array([ 1000,   223, 12998, ...,   796,   436,  1051], dtype=int64)

In [162]:
items.sort()
items

array([        2,         9,        22,        31,        33,        36,
              39,        41,        44,        48,        68,        74,
              84,        95,        97,       104,       107,       111,
             113,       119,       120,       121,       132,       148,
             156,       163,       171,       179,       180,       184,
             187,       195,       201,       211,       219,       227,
             233,       234,       241,       243,       247,       249,
             251,       252,       254,       257,       264,       269,
             274,       279,       281,       288,       289,       296,
             299,       304,       305,       308,       314,       315,
             320,       322,       328,       329,       330,       335,
             337,       340,       344,       345,       346,       352,
             353,       355,       361,       363,       368,       369,
             377,       378,       385,       393, 

In [15]:
atlas_indices=np.unique(atlas)

In [16]:
atlas_indices

array([   0,    3,   11,   12,   13,   14,   15,   17,   18,   19,   20,
         21,   22,   25,   26,   28,   35,   36,   37,   38,   39,   41,
         42,   43,   44,   45,   47,   48,   49,   50,   51,   56,   57,
         71,   80,   81,   82,   83,   84,   85,   89,   90,   91,   92,
         93,   94,   96,   97,   98,   99,  100,  101,  103,  104,  105,
        106,  107,  108,  110,  111,  112,  113,  114,  115,  116,  117,
        118,  119,  121,  122,  124,  125,  126,  128,  129,  131,  149,
        154,  159,  165,  172,  173,  174,  185,  186,  187,  188,  194,
        199,  205,  215,  216,  221,  225,  236,  244,  245,  246,  260,
        268,  274,  275,  279,  280,  281,  282,  283,  287,  288,  292,
        295,  297,  300,  301,  304,  306,  308,  317,  318,  320,  321,
        322,  323,  324,  336,  337,  338,  339,  342,  343,  347,  348,
        349,  350,  351,  352,  353,  357,  358,  359,  360,  361,  362,
        366,  367,  368,  369,  370,  371,  372,  3

In [17]:
ctx_id= np.intersect1d(items,atlas_indices)

In [18]:
ctx_id

array([  22,   36,   39,   41,   44,   48,   84,   97,  104,  107,  111,
        113,  119,  121,  187,  274,  279,  281,  288,  304,  308,  320,
        322,  337,  352,  353,  361,  368,  369,  378,  393,  394,  409,
        417,  430,  440,  441,  442,  448,  453,  461,  476,  497,  500,
        501,  520,  527,  533,  540,  541,  556,  565,  573,  582,  590,
        601,  613,  625,  635,  649,  656,  667,  669,  675,  680,  694,
        696,  699,  707,  729,  738,  750,  755,  759,  767,  774,  783,
        786,  800,  801,  805,  806,  816,  819,  821,  844,  847,  849,
        854,  862,  865,  869,  873,  879,  882,  886,  888,  889,  902,
        905,  906,  921,  927,  929,  935,  950,  965,  981,  985,  988,
        990,  996, 1002, 1005, 1006, 1010, 1011, 1015, 1018, 1053, 1054,
       1057, 1058, 1062, 1066, 1074, 1081, 1094, 1106, 1127, 1128])

In [171]:
def create_mask(x):
    #create mask based on selected atlas index (an int)
    mask=np.zeros_like(atlas)
    for i in x:
        mask_idx= atlas==i
        mask[mask_idx]=1
    return mask

In [170]:
x= [977, 981, 988]

In [ ]:
mask1=create_mask(ctx_id)
viewer.add_labels(mask1, name='mask')

In [201]:
mask1=create_mask([312782656])
viewer.add_labels(mask1, name='mask')

<Labels layer 'mask [3]' at 0x131444ec5f8>

In [200]:
# find non-labled ids
all_id=np.asarray(na.atlas_labels.id)
for i in atlas_indices:
    if i not in all_id:
        print(i)

0
182305696
182305712
312782560
312782592
312782656
484682464
526157184
526322272
527696992
549009216
560581568
563807424
576073728
589508416
589508480
599626944
606826624
606826688
607344832
614454272
